version: '3.8'

services:
  server1:
    build: .
    ports:
      - "8001:8080"
    environment:
      - "RUST_BACKTRACE=1"
    networks:
      - server-network
    command: "-s server1:8080 -s server2:8080"

  server2:
    build: .
    ports:
      - "8002:8080"
    environment:
      - "RUST_BACKTRACE=1"
    networks:
      - server-network
    command: "-s server1 -s server2"

networks:
  server-network:
    driver: bridge
